services:
  mongo:
    image: mongo:7
    container_name: syncspace-mongo
    ports:
      - "27017:27017"
    volumes:
      - syncspace-mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: syncspace-redis
    ports:
      - "6380:6379"
    volumes:
      - syncspace-redis-data:/data

volumes:
  syncspace-mongo-data:
  syncspace-redis-data:
